module.exports = Object.freeze({
    ACTION_TYPE: {        
        UPDATE_EDIT_FLOW: 'UPDATE_EDIT_FLOW',
        UPDATE_INVOICE_DETAILS: 'UPDATE_INVOICE_DETAILS',
        UPDATE_CURRENT_STEP: 'UPDATE_CURRENT_STEP',
        CLEAR_FORM: 'CLEAR_FORM',
        UPDATE_DEAL_CREATION_DETAILS: 'UPDATE_DEAL_CREATION_DETAILS'
    }
});
    